version: "3.8"

services:
  cardio-ml:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: cardio-ml
    restart: always
    depends_on:
      - mongodb
    environment:
      CARDIO_MONGO_HOST: mongodb
      CARDIO_MONGO_DB_NAME: ${CARDIO_MONGO_DB_NAME:-cardio}
      CARDIO_MONGO_USER: ${CARDIO_MONGO_USER:-admin}
      CARDIO_MONGO_PASSWORD: ${CARDIO_MONGO_PASSWORD:-password}
      CARDIO_HOST: 0.0.0.0
      CARDIO_SECRET_KEY: ${CARDIO_SECRET_KEY:-secret_key}
    ports:
      - "127.0.0.1:${CARDIO_PORT:-8080}:80"

  mongodb:
    image : mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CARDIO_MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${CARDIO_MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${CARDIO_MONGO_DB_NAME:-cardio}
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - ${CARDIO_MONGO_PORT:-27017}:27017
